class CfgAmmo {
	class ShellBase;
	class 101_AA_fim92f_proximity: ShellBase
	{
		typicalSpeed=100;
		explosive=1;
		cost=300;
		model="\A3\Weapons_f\empty";
		airFriction=0;
		timeToLive=1;
		explosionTime=0.001;
		soundFly[]=
		{
			"",
			1,
			1
		};
		soundEngine[]=
		{
			"",
			1,
			4
		};
		indirectHit=50;
		indirectHitRange=40;
		explosionEffects="AAMissileExplosion";
		hit=60;
		soundHit[]=
		{
			"",
			100,
			1
		};
		soundHit1[]=
		{
			"A3\Sounds_F\arsenal\weapons\Launchers\Titan\Explosion_titan_missile_01",
			2.51189,
			1,
			1900
		};
		soundHit2[]=
		{
			"A3\Sounds_F\arsenal\weapons\Launchers\Titan\Explosion_titan_missile_02",
			2.51189,
			1,
			1900
		};
		soundHit3[]=
		{
			"A3\Sounds_F\arsenal\weapons\Launchers\Titan\Explosion_titan_missile_03",
			2.51189,
			1,
			1900
		};
	};
	class 101_AA_sa20_proximity: ShellBase
	{
		typicalSpeed=100;
		explosive=1;
		cost=300;
		model="\A3\Weapons_f\empty";
		airFriction=0;
		timeToLive=1;
		explosionTime=0.001;
		soundFly[]=
		{
			"",
			1,
			1
		};
		soundEngine[]=
		{
			"",
			1,
			4
		};
		indirectHit=80;
		indirectHitRange=60;
		explosionEffects="HelicopterExplosionEffects2";
		hit=60;
		soundHit[]=
		{
			"",
			100,
			1
		};
		soundHit1[]=
		{
			"A3\Sounds_F\arsenal\weapons\Launchers\Titan\Explosion_titan_missile_01",
			2.51189,
			1,
			1900
		};
		soundHit2[]=
		{
			"A3\Sounds_F\arsenal\weapons\Launchers\Titan\Explosion_titan_missile_02",
			2.51189,
			1,
			1900
		};
		soundHit3[]=
		{
			"A3\Sounds_F\arsenal\weapons\Launchers\Titan\Explosion_titan_missile_03",
			2.51189,
			1,
			1900
		};
	};
};